import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {withAuthenticator} from "@aws-amplify/ui-react"
import { User } from 'src/models'
import { DataStore } from '@aws-amplify/datastore'
import { useEffect } from 'react'
import { listUsers } from 'src/graphql/queries'
import { API,graphqlOperation,Auth } from "aws-amplify"
 function Home() {
  useEffect(() => {
    const ddd = async()=>{
      const fffr = await DataStore.query(User)
      const fff = await API.graphql(graphqlOperation(listUsers))
      console.log(fff)
      console.log(fffr)
    }
    
    ddd()
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg">
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

      
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
export default withAuthenticator( Home)